<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>

    <IsPackable>false</IsPackable>
    <RootNamespace>NetFabric.Numerics.Benchmarks</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetFabric.Numerics\NetFabric.Numerics.csproj" />
  </ItemGroup>

</Project>
