name: .NET

on:
  push:
    branches: 
    - main
    paths:
    - src/**
    - .github/workflows/dotnet.yml
  pull_request:
    branches:
    - main
    paths:
    - src/**
    - .github/workflows/dotnet.yml
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Setup .NET 7.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build --no-restore -c:Release

    - name: Test Solution
      run: dotnet test --no-build --verbosity normal
